name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*.exe
          build/*.dmg
          build/*.AppImage
          build/*.blockmap
          latest.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}